
version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - monitoring
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend22:
    image: taraknathjana09/backend_app_diabetic_prediction:v1.2
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "443:3000"
    networks:
      - monitoring
    environment:
      DATABADE_URL: "mongodb://mongodb:27017/"
      API_URL:  "http://ml_backend.taraknathjana.com/predict"
      ACCESS_TOKEN_EXPAIRY : "1d"
      ENV ACCESS_TOKEN_SECRET : 3ODkwIiwibmFtZSIkwIiwibmFtZSI6Ikpva
      ENV REFRESH_TOKEN_SECRET : GIjoxNTkwIiwibmFtZSIE2MjM5MDIyfQ
      ENV REFRESH_TOKEN_EXPAIRY : "10d"
      ENV CROSE_ORIGIN : "https://diabetic-prediction-fontend.vercel.app"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  
networks:
  monitoring:

volumes:
  mongodb_data: